script_template: inno_setup.iss
app_id: 728B3532-C74B-4870-9068-BE70FE12A3E6
app_name: FxClashX
publisher: pluralplay
publisher_url: https://github.com/kuruse205/FxClashX
display_name: FxClashX
executable_name: FxClashX.exe
output_base_file_name: FxClashX.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: ru
  - lang: en
privileges_required: admin